version: "3"
services:
  db:
    image: postgres:14
    container_name: area_db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - area-db-data:/var/lib/postgresql/data
      - ./postgres:/etc/postgresql/14/main
    network_mode: "host"
  server:
    build: ./server
    container_name: area_server
    restart: always
    env_file:
      - "./server/.env"
    network_mode: "host"
    depends_on:
      - "db"
networks:
  back:
volumes:
  area-db-data: