version: "3"
services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - area-db-data:/var/lib/postgresql/data
      - ./postgres:/etc/postgresql/14/main
volumes:
  area-db-data: