name: Publish backend
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    permissions: write-all
    name: Publish binaries
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Build backend
      run: cd server && npm install && npm run build
    - name: Zip backend
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r backend.zip ./server/dist
    - name: Upload backend to release
      uses: svenstaro/upload-release-action@v2
      with:
        release_name: ${{ github.ref }}-Build
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./backend.zip
        asset_name: backend.zip
        tag: ${{ github.ref }}
        overwrite: false
        body: "Amazing trirea release !"